export const ACT_APP_CHANGE = "ACT_APP_CHANGE";
export const ACT_GAME_CHANGE = "ACT_GAME_CHANGE";
export const ACT_GIF_CHANGE = "ACT_GIF_CHANGE";
export const ACT_USER_CHANGE = "ACT_USER_CHANGE";
export const ACT_WORKPLAN_CHANGE = "ACT_WORKPLAN_CHANGE";
